baseURL = 'https://nichom01.github.io/content-management/'
languageCode = 'en-us'
title = 'Neversoft'
theme = "hugo-theme-monochrome"

[params]
footer = "Copyright © 2025 Neversoft. Documentation for the Supplier Management System."

# Navbar Menu
[[menu.navbar]]
name = "Home"
url = "/"
weight = 10

[[menu.navbar]]
name = "Posts"
url = "/posts/"
weight = 20

[[menu.navbar]]
name = "About"
url = "/posts/about/"
weight = 30

# Footer Menu
[[menu.footer]]
name = "About"
url = "/posts/about/"
weight = 10

[[menu.footer]]
name = "Functional Specification"
url = "/posts/functional-specification/"
weight = 20

[[menu.footer]]
name = "System Description"
url = "/posts/system-description/"
weight = 30

